config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'main', to: 'pages#main'
  get 'home', to: 'pages#home'

  resources :universities
  resources :careers
  resources :roles
  resources :users
  resources :professors
  resources :courses
  resources :materials
  resources :enrollments
  resources :notifications

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Rutas para OmniAuth
  get '/auth/:provider/callback', to: 'sessions#google_auth'
  get '/auth/failure', to: redirect('/')

  # Rutas de errores
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable_entity', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/career.rb
class Career < ApplicationRecord
  belongs_to :university
  has_many :users
end

app/models/category.rb
# app/models/category.rb
class Category < ApplicationRecord
  # Aquí puedes agregar validaciones y relaciones necesarias
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :professor
  has_many :materials
  has_many :enrollments
  has_many :users, through: :enrollments

  validates :nombre, presence: true
  validates :descripcion, presence: true
    # Supongamos que los cursos destacados son aquellos con una calificación de 4.5 o superior
  scope :featured, -> { where('rating >= ?', 4.5).limit(4) } # Ajusta el criterio según tus necesidades

  # O podrías definirlo como un método de clase

  def self.featured
    where("rating >= 4.5")
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :course
end

app/models/notification.rb
# app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  after_create_commit { broadcast_notification }

  private

  def broadcast_notification
    ActionCable.server.broadcast "notifications_#{user.id}", {
      message: render_notification(self)
    }
  end

  def render_notification(notification)
    ApplicationController.renderer.render(partial: 'notifications/notification', locals: { notification: notification })
  end
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :user
  has_many :courses
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/university.rb
class University < ApplicationRecord
  has_many :careers
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :role
  belongs_to :career, optional: true
  has_many :enrollments
  has_many :courses, through: :enrollments
  has_many :notifications

  validates :nombre_completo, presence: true
  validates :email, presence: true, uniqueness: true
  validates :user_name, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, if: -> { new_record? || !password.nil? }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.nombre_completo = auth.info.name
      user.email = auth.info.email
      user.user_name = auth.info.email.split('@').first
      user.password = SecureRandom.hex(15)
    end
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: %i[show edit update destroy]

  def index
    @materials = Material.all
  end

  def show
  end

  def new
    @material = Material.new
  end

  def edit
  end

  def create
    @material = Material.new(material_params)

    if @material.save
      redirect_to @material, notice: 'Material was successfully created.'
    else
      render :new
    end
  end

  def update
    if @material.update(material_params)
      redirect_to @material, notice: 'Material was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @material.destroy
    redirect_to materials_url, notice: 'Material was successfully destroyed.'
  end

  private

  def set_material
    @material = Material.find(params[:id])
  end

  def material_params
    params.require(:material).permit(:titulo, :contenido, :course_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]  
  end
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/materials/_form.html.erb
<%= form_with(model: material, local: true) do |form| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
        <% material.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :contenido %>
    <%= form.text_area :contenido %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.collection_select :course_id, Course.all, :id, :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Edit Material</h1>
<%= render 'form', material: @material %>
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<h1>Materials</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.titulo %></td>
        <td><%= material.contenido %></td>
        <td><%= material.course.nombre %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New Material</h1>
<%= render 'form', material: @material %>
<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @material.titulo %>
</p>

<p>
  <strong>Content:</strong>
  <%= @material.contenido %>
</p>

<p>
  <strong>Course:</strong>
  <%= @material.course.nombre %>
</p>

<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>