config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'main', to: 'pages#main'
  get 'home', to: 'pages#home'

  resources :universities
  resources :careers
  resources :roles
  resources :users
  resources :professors
  resources :courses
  resources :materials
  resources :enrollments
  resources :notifications

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Rutas para OmniAuth
  get '/auth/:provider/callback', to: 'sessions#google_auth'
  get '/auth/failure', to: redirect('/')

  # Rutas de errores
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable_entity', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/career.rb
class Career < ApplicationRecord
  belongs_to :university
  has_many :users
end

app/models/category.rb
# app/models/category.rb
class Category < ApplicationRecord
  # Aquí puedes agregar validaciones y relaciones necesarias
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :professor
  has_many :materials
  has_many :enrollments
  has_many :users, through: :enrollments

  validates :nombre, presence: true
  validates :descripcion, presence: true
    # Supongamos que los cursos destacados son aquellos con una calificación de 4.5 o superior
  scope :featured, -> { where('rating >= ?', 4.5).limit(4) } # Ajusta el criterio según tus necesidades

  # O podrías definirlo como un método de clase

  def self.featured
    where("rating >= 4.5")
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :course
end

app/models/notification.rb
# app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  after_create_commit { broadcast_notification }

  private

  def broadcast_notification
    ActionCable.server.broadcast "notifications_#{user.id}", {
      message: render_notification(self)
    }
  end

  def render_notification(notification)
    ApplicationController.renderer.render(partial: 'notifications/notification', locals: { notification: notification })
  end
end

app/models/professor.rb
class Professor < ApplicationRecord
  belongs_to :user
  has_many :courses
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/university.rb
class University < ApplicationRecord
  has_many :careers
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :role
  belongs_to :career, optional: true
  has_many :enrollments
  has_many :courses, through: :enrollments
  has_many :notifications

  validates :nombre_completo, presence: true
  validates :email, presence: true, uniqueness: true
  validates :user_name, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, if: -> { new_record? || !password.nil? }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.nombre_completo = auth.info.name
      user.email = auth.info.email
      user.user_name = auth.info.email.split('@').first
      user.password = SecureRandom.hex(15)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]  
  end
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<!-- app/views/layouts/_navbar.html.erb -->
<div class="navbar-item has-dropdown is-hoverable">
  <a class="navbar-link" href="#">
    <i class="fas fa-bell"></i>
    <span id="unread-count" class="badge is-danger"><%= @unread_count %></span>
  </a>

  <div id="notifications-dropdown" class="navbar-dropdown is-right">
    <% @notifications.each do |notification| %>
      <%= render partial: 'notifications/notification', locals: { notification: notification } %>
    <% end %>
    <hr class="navbar-divider">
    <a class="navbar-item" href="<%= notifications_path %>">Ver todas las notificaciones</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UBBCSA</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css', media: 'all' %>
</head>
<body>


        <%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<!-- app/views/shared/_navbar.html.erb -->
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <%= link_to image_tag('logo.png', alt: 'UBBCSA Logo'), main_path, class: 'navbar-item' %>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item is-active" href="#">
        <i class="fas fa-home"></i> <span class="navbar-title">Inicio</span>
      </a>

      <a class="navbar-item" href="#">
        <i class="fas fa-book"></i> <span class="navbar-title">Cursos</span>
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link" href="#">
          <i class="fas fa-bell"></i>
          <span class="badge is-danger"><%= @unread_count %></span> <!-- Contador de notificaciones no leídas -->
        </a>

        <div class="navbar-dropdown is-right">
          <% if @notifications.present? %>
            <% @notifications.limit(5).each do |notification| %>
              <a class="navbar-item" href="<%= notification_path(notification) %>">
                <% if notification.read %>
                  <p><%= notification.mensaje %></p>
                <% else %>
                  <p><strong><%= notification.mensaje %></strong></p>
                <% end %>
              </a>
            <% end %>
          <% else %>
            <a class="navbar-item">No tienes notificaciones</a>
          <% end %>
        </div>
      </div>
    </div>

      <a class="navbar-item" href="#">
        <i class="fas fa-search"></i> <span class="navbar-title">Buscar</span>
      </a>

      <a class="navbar-item" href="#">
        <i class="fas fa-save"></i> <span class="navbar-title">Guardados</span>
      </a>

      <a class="navbar-item" href="#">
        <i class="fas fa-user"></i> <span class="navbar-title">Perfil</span>
      </a>
    </div>
  </div>
</nav>